version: '3.7'

services:
  dev_rabbitmq:
    image: rabbitmq:3-management
    container_name: mongorr_rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/mnesia
      
  dev_redis:
    image: redis
    container_name: mongorr_redis
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - redis_data_volume:/data

  dev_mongodb:
    image: mongo:latest
    container_name: "mongorr_mongodb"
    environment:
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data_volume:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null 

volumes:
  rabbitmq_data_volume:
  redis_data_volume:
  mongodb_data_volume:
